name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'origin/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'ITN-[0-9]+ feat|test|scaffold|fix|docs|ops|refactor|perf|style|upgrade\(([A-Za-z]+( [A-Za-z]+)+)\)/g'
          flags: 'gm'
          error: 'Your commit message does not match the ITN-X tag(desc)'
