name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request_review, pull_request_review_comment]
  pull_request:
    types: [opened, edited, review_requested, ready_for_review, issue_comment]
jobs:
  build: 
  pull_request title check:
      runs-on: ubuntu-latest

      steps:
        - uses: action/setup-python@v4
          with:
            python-version: '3.10'
        - run: python -m pip install --upgrade pip
        - name: PR title check
          - run: python3 script.py ${{ github.event.pull_request.title }}