name: check PR title
on: 
  pull_request:
    types: [opened, edited, review_requested, ready_for_review]
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - name: PR title check
        run: python3 .github/workflows/script.py "${{ github.event.pull_request.title }}"