name: Elixir CI

on: 
  push:
    branches: ["ITN-2_feat(add_mix_test)"]
  pull_request:
    branches: ["ITN-2_feat(add_mix_test)"]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opt: ['27.0']
        elixir: ['1.18.1']

    steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}} # [Required] Define the Elixir version
        otp-version: ${{matrix.opt}}      # [Required] Define the Erlang/OTP version
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test